# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Raja Biswas
email: raja_biswas@u.nus.edu
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning Explorations, Life Adventures
baseurl: '/'
url: https://rbiswasfc.github.io
twitter_username: mmistakes
github_username: mmistakes
minimal_mistakes_skin: "contrast"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
include:
  - _pages

# Site Author
author:
  name             : "Raja Biswas"
  avatar           : "/images/raja_2.JPG"
  bio              : "Patient Endurance"
  location         : "Singapore"
  email            : raja_biswas@u.nus.edu
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rbiswasfc"
    - label: "LinkedIn"
      icon:  "fab fa-fw fa-linkedin"
      url:   "https://www.linkedin.com/in/raja-biswas/"

repository: rbiswasfc/rbiswasfc.github.io

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/raja_biswas"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/raja.biswas.9"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rbiswasfc"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/_rbiswas/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
